// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpZc+M2Ev4rKG4e7F3qsD1X9LKlSMpYFY+ssuXsbo28KohsSYhBgAFA24pL/30LBy+RlO1MZmoe9mVq",
	"TIGNRh9ff93gkxfwKOYMmJJe78mLscARKBDmrwmoBy7uxuEUq41+EIIMBIkV4czrecPBJ0SYVJgFgMZD",
	"dBQGUSt90CIhongJ9NjzPXjEUUzB63kPsGytBGcKWNiSIO5JAJ7vES0v1rv4HsORXsns5gsSer4n4PeE",
	"CAi9nhIJ+J4MNhBhq7FSIPTr//2MW390Wz/eHrn/tG6fuv67k136/PifP3i+p7axFi+VIGzt7Xa7VJo5",
	"8kgILqpHvfp5gN5/6L5H2lyUYKYQ6JVIgIw5k/oMseAxCEVA2vcVJrQq6TyJMGsJwCFeUkDwGFPMsP4R",
	"yRgCsiIBUhypDZGIB0EiBDBjoj29tc2spat73DDyewKIhMAUWREQaMWFFWm1LglecRFh5fW8RJCWgBU0",
	"7igVVomsOdNsNkX2RxTwsCSUMHV2mgsjTMEahJamiKI1yl9vuFBoUzaTTKIIi22dUvbBvhTjR6R/SzUC",
	"lkRe77M3nvzavxgPF/2rjzefRpOZ53uTy9ni58ubydDzvf7F1ag//M9i9O/x9eza873p6OrT+Pp6fDlZ",
	"DEeT8Ugvupn0b2bno8lsPOjPzJPxZDa6mvQv7I+/9scX/Z8uRp7v/dwfX4yGi+nVaHA5GY5n48uJd/ty",
	"o++Ksf/Z/pqa7jZbzZe/QaC0Nc4B07pctc9TJ0nC1hQUZzp+eSKCavzGtSk/wIwzEmCK9O+Ir5DaQFFI",
	"nukbq4nWH4eXjG7T3H15WBV1rpH9inC4chraiMgToyT17oNsOdRJoakVC35PQhDtMIjahHeyUzU68Nnj",
	"JrEiUV3gQ8BZaJyjFd0AckqgVAltCqEgLGp99q7bbdy0kG33IKTZp7rt3ibLhNAQpeuLBjppd9vd549Y",
	"H7OZGx3M5xs4g1TC2fceWxjiVhZeOdxLLdj54tb3YpoITLPA0LtkIZ6VDMLWCcWiGJpuv1c4Xh/ul2QJ",
	"goECOXWLzomrnzgMibYrptNCNq0wleDv2T2X0sqAP/WFBKUIW0t0pA0JUiHO6Pa4kqQBTaQCsSBxjV9T",
	"oW4RGk/RPaYJtNEAM7QEhPXfJNQ/PBC1IcwEXbp8MB5e+XM29yacwdwzJWQDOKQgZRqZ0ke6mkREKQjN",
	"Cpwo3sJSkjWLgKn2nNUlKeMhLGIuDhntqVpDIvxIIo3iZ6fv3733vYgw93e3q7OgGvVlk3zCsYYsvTHS",
	"LEPqSjvhIUz1E2MciY6MsJbZ4rg9Z//aAEOxAAlMGTshxpHgiXbQgsI9UB8FArACmctyjtSv6zdKy9E8",
	"5TZzz0+LPkiUG8VY8oLj8CdMdYUXaImDO2BhyZw56EugECjLW5qMWfFB2TQXmqqhVJC2S4RVsEEKizUo",
	"FPNQVnfe1eiSh/W1wqoG5uriXiRMQ4CBetBBb0mVjfr2nA04U5gwaQIUByrBFP3yQWb5Yuu8cUKIMAsz",
	"gYTZICKcWdu9PH/6eSRDqMM8kSBSlSEspFVdhMOjhilMFySuqWwj9ysaT6UWveFS2YCseD7NNHS0EjxC",
	"bQujbVpY0yZsLUDKz7caIYiCqN7j7gEWAm+/SthIbSOLAzEP06ivi9j6Kj0reDeLklonF/jcwPrBuCHN",
	"P8/3ikYslJZSjaqtYrmSrv2p6ul+yHgPEuAAgrA1wnXKZ2S9EoLmQIt6SjAjEUiFoxg9aBTS0e+gI+MG",
	"D1gWjJJBZogVtIzQFzASEn7V5i7CjxfA1ppPvjszqJ3+eeK/vn979jR3mfX1qX4QsPJ63t86eaPbcf1e",
	"Zx+rdn4D7c3oo2G9DfTReUZ2GszwPA+OIXhOZRd6uriXqTOm9HLl9T6/7HX72u52XytDT8MvDkiKpUJW",
	"0J+Nyj0SaWzzaoaYueQpnybsSoQxXeGVCKJ7+jqGmL60y6HjgkhVNeIUrwkzpYoSTe1WFRumeSYrcMHg",
	"US1ivIaF4ndQQ+dn+rGBYAFKELjXkGT99KiQflNvKEAmVMm6ypX+1HvKS8kLQqpaYHbNkPoJFA6xwgcy",
	"LXJLzFHSjAtMJa8YxUCR/IIyNkik4hG6g23LsEAUYyJsMVZ4vTaozkK0IlSBaChpdmzVzHayUqAXoqPh",
	"5Lp10j17m+Po62Gy5f7394MTLquajHFwWL9slc5tYTvQ69oq87rUNYa5bQ6Gawd79TU25Yh2RKY9YvRo",
	"KrTtORtrPNbNh6WLmlGbGdJ+khk+YaO4jhtGhRh9QfxnIa2LSNrZ7OW97gxCWBFmYtTFV97nF8nboR21",
	"nLQARISN7TsnVYKXItRik/anB8WWmlntxGLXUoM0Aq8MebfLkFnWLnY39oACM6kt0rLdz9FsMO3cDKfH",
	"prnEcUydc93689ls2tH/XLfREBSIiDCwrmwghXOm+BrUBoTtz4zXDR8LDNgVGivCUNko1vMpl8xxv6BX",
	"DXvU3Nnsv6gnsiXKWhjDHkWJVLr1LhjpuGb/22fLYXF7P4/VNPYOpVvDtG1gJsIqHRG60V5TZWrP2XQ0",
	"GY4nH3u1/Qp6wMREhXYp5O0OKs0GzKi1l5NkiXQGYovg6Cij9p2ssSZRBCHBCujWL2+MV27IkfZsunEc",
	"ji5Gs9Ew3yKj7IwrtOIJC3VMuF6uHAzufJ7vGTU933PSagMiS8rn0t6OSfYNWy30teVkmo4u7GRIh4Nl",
	"YlFCFYmphTuJsAC7JYRlir5RKj44kalphCnlgaEr5VHJXp/uF2c/tmM2HWs530ranJ2cnr3xXz/neX7a",
	"WX+SbNRprJhEyzKD/9A9pMu7t2/P3hZ0OandV3DFA+7QcoUTqmXNBro5ra9v2Rt54NnlN8OpDrTcdfZx",
	"tas3E5oG383S8Y1QiFu+vsTBnU5MN9IpnP6Lz78HUkalOiR64djUOncvAdyr+ezIhJUNNTO+xApTvq7k",
	"05/pCvcqYpXQ7sw13IqbRp4zhQOV565poaeCu04lEdTln+x1OmuiNsmyHfCooxvr2C7rHOozqrT1anQ9",
	"Q/3p2EBKhBk2THUPWSQ6qtZNeTxnnBULqoNAqcNkCRtMV7oEDAef2nM22xDp9qGUP0jUH5n7PhZiEVoa",
	"E3AmiVTAgi3CgeBS6nczHSyyUhIAk1AwUT/GwQbQqblWKFvo4eGhjc3PbS7WHfeu7FyMB6PJ9ah12u62",
	"NyqihavEIptN8yvN+dSX+hyF24f0UmPnezwGhmPi9byzdrf9xt1UmHDp4Jh07k8wjTf4pJP1jL0nbw01",
	"WafbPoQpbe7rLFGJbSNo7n6TOLaDq6wCjkMnapL3qMX7+c9PlfG2SVWHbK7NM9VOohiEaf7Su/bfEzDX",
	"qc4PEX60XaUkf5jLmux+PUOxtwfR4cQA82FwaG5VD/SnddoW+t+iqvuUyUw3bIUyvjrtdtNEBWbcVmB5",
	"nd+kvR3L5b2A9ZsG38BALbrLtAmHEMkkCEDKVUKpIedvDmoTC76kEP3jdVrZrxdq9Bkze9WTXicV4mjn",
	"e2+/rSqODOqkAGG/SDDgml7yuwQqhL3CazPPyR7dmhpfN1wZmC7VEKyHxvyrg8TjSu5ZUZOsJziYfJex",
	"Y60BJcBU4aJgPCzEuJHVRuOVIaAO2kN/ztI+0DQxlKI1MK0LIMzQeNieszm7srXVtrZHOqP7o2nr5PT0",
	"uDdnLXTSeneGgg0WODBATjlb6+fXCgt3c4UR5Q8gAiwBUVCaMHOBQrImSq901yyGzlVWSt8Bi/TNMGSz",
	"jTfApH5vxEIrP5dpl87Ziz/+2Utx89VPHml/7Qi5FihMYvzEw+1fjRE2CcpfMO0q0HTydbatJ53pVdl3",
	"hklbynHoo4hIqYlM1uGsCNDQ3jUT91KBwkur+Y/fTvNsKqZjXupuzLRkmOrGZIvgkUhl7vWyhingbEWJ",
	"Zb/fHdo6yMyBrgZud34DCUo/jGjiQlegEuFubjelj5DchCHHgTL6fgR1nn9C9JXK+Hn6VUejj4lE6ddG",
	"Zau5r5MGGwiKNnMSD1msdBlhDEah7qZ8aJ4jnH8Y+GX1zMprrGd1dsqXdMofg9aQqzfNQ1x7wjq8efPt",
	"UiFVJpv8fJfJ6Jx+MBn9xlQzXPNFEbPcor0r3roM/GrB0v2W5e4QCf9/AO4F4EdQz5QCN/6u58G/fGju",
	"vbMev2NCwslu+Owz0MCaz4Nlzg1T0Pab4IaSFQTbgIIdihjGXCspO9Xudve/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
