// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS      ErrorType = "ALREADY_EXISTS"
	FAILEDPRECONDITION ErrorType = "FAILED_PRECONDITION"
	INTERNAL           ErrorType = "INTERNAL"
	INVALIDARGUMENT    ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           ErrorType = "NOT_FOUND"
	PERMISSIONDENIED   ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED    ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE        ErrorType = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case FAILEDPRECONDITION:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesStateType.
const (
	ClusterIP    KubernetesStateType = "ClusterIP"
	LoadBalancer KubernetesStateType = "LoadBalancer"
	NodePort     KubernetesStateType = "NodePort"
)

// Valid indicates whether the value is a known member of the KubernetesStateType enum.
func (e KubernetesStateType) Valid() bool {
	switch e {
	case ClusterIP:
		return true
	case LoadBalancer:
		return true
	case NodePort:
		return true
	default:
		return false
	}
}

// Defines values for NetworkSpecRoutingLevel.
const (
	NetworkSpecRoutingLevelApplication NetworkSpecRoutingLevel = "application"
	NetworkSpecRoutingLevelNetwork     NetworkSpecRoutingLevel = "network"
)

// Valid indicates whether the value is a known member of the NetworkSpecRoutingLevel enum.
func (e NetworkSpecRoutingLevel) Valid() bool {
	switch e {
	case NetworkSpecRoutingLevelApplication:
		return true
	case NetworkSpecRoutingLevelNetwork:
		return true
	default:
		return false
	}
}

// Defines values for NetworkSpecServiceType.
const (
	NetworkSpecServiceTypeNetwork NetworkSpecServiceType = "network"
)

// Valid indicates whether the value is a known member of the NetworkSpecServiceType enum.
func (e NetworkSpecServiceType) Valid() bool {
	switch e {
	case NetworkSpecServiceTypeNetwork:
		return true
	default:
		return false
	}
}

// Defines values for NetworkStatus.
const (
	DELETED NetworkStatus = "DELETED"
	PENDING NetworkStatus = "PENDING"
	READY   NetworkStatus = "READY"
)

// Valid indicates whether the value is a known member of the NetworkStatus enum.
func (e NetworkStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case PENDING:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// Defines values for PortSpecProtocol.
const (
	TCP PortSpecProtocol = "TCP"
	UDP PortSpecProtocol = "UDP"
)

// Valid indicates whether the value is a known member of the PortSpecProtocol enum.
func (e PortSpecProtocol) Valid() bool {
	switch e {
	case TCP:
		return true
	case UDP:
		return true
	default:
		return false
	}
}

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type Error type code
	Type ErrorType `json:"type"`
}

// ErrorType Error type code
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status string `json:"status"`

	// Type Resource type identifier
	//
	// Example: k8s-network-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 1.0.0
	Version *string `json:"version,omitempty"`
}

// KubernetesProviderHints Kubernetes-specific Service settings (request only)
type KubernetesProviderHints struct {
	// ClusterIp Specific cluster IP value. Can be a valid IP within the cluster CIDR,
	// "None" for headless services, or omitted for auto-assignment.
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// NodePorts Map of port names to NodePort values (30000-32767).
	// When present with no routing_level, creates NodePort Service.
	// With routing_level "network", specifies node_ports for LoadBalancer backend.
	NodePorts *map[string]int32 `json:"node_ports,omitempty"`

	// Selector Label selector to match target pods
	Selector *map[string]string `json:"selector,omitempty"`
}

// KubernetesState Kubernetes-specific runtime state (response only).
// Contains the actual K8s Service type created and runtime information.
type KubernetesState struct {
	// ClusterIp Auto-assigned or user-specified cluster IP
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// ExternalIps External IPs or hostnames for LoadBalancer services (from .status.loadBalancer.ingress[])
	ExternalIps *[]string `json:"external_ips,omitempty"`

	// Selector Label selectors used for pod routing
	Selector *map[string]string `json:"selector,omitempty"`

	// Type The actual Kubernetes Service type created
	Type *KubernetesStateType `json:"type,omitempty"`
}

// KubernetesStateType The actual Kubernetes Service type created
type KubernetesStateType string

// Network Network resource representing a Kubernetes Service instance
type Network struct {
	// CreateTime Timestamp when the network service was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id DCM instance ID (dcm-instance-id label)
	//
	// Example: web-frontend-service
	Id *string `json:"id,omitempty"`

	// Kubernetes Kubernetes-specific runtime state (response only).
	// Contains the actual K8s Service type created and runtime information.
	Kubernetes *KubernetesState `json:"kubernetes,omitempty"`

	// Path Resource path identifier
	//
	// Example: networks/web-frontend-service
	Path *string `json:"path,omitempty"`

	// Spec Network specification for creating a Kubernetes Service.
	// Implements the portable network service type schema.
	Spec   NetworkSpec    `json:"spec"`
	Status *NetworkStatus `json:"status,omitempty"`

	// UpdateTime Timestamp when the network service was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// NetworkList Paginated list of network service instances
type NetworkList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string    `json:"next_page_token,omitempty"`
	Results       *[]Network `json:"results,omitempty"`
}

// NetworkMetadata Resource metadata for identification
type NetworkMetadata struct {
	// Labels Custom key-value pairs for tagging and filtering
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes Service name (DNS-1035 label)
	Name string `json:"name"`

	// Namespace Kubernetes namespace where the Service was created
	Namespace *string `json:"namespace,omitempty"`
}

// NetworkSpec Network specification for creating a Kubernetes Service.
// Implements the portable network service type schema.
type NetworkSpec struct {
	// Metadata Resource metadata for identification
	Metadata NetworkMetadata `json:"metadata"`

	// Ports Port definitions for the service
	Ports []PortSpec `json:"ports"`

	// ProviderHints Provider-specific hints from the catalog
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// RoutingLevel Traffic routing level. "network" for transport-level (TCP/UDP),
	// "application" for HTTP/HTTPS. Determines the Kubernetes Service type
	// together with the presence of node_ports in provider_hints.
	RoutingLevel *NetworkSpecRoutingLevel `json:"routing_level,omitempty"`

	// ServiceType Service type identifier (must be "network")
	ServiceType NetworkSpecServiceType `json:"service_type"`
}

// NetworkSpecRoutingLevel Traffic routing level. "network" for transport-level (TCP/UDP),
// "application" for HTTP/HTTPS. Determines the Kubernetes Service type
// together with the presence of node_ports in provider_hints.
type NetworkSpecRoutingLevel string

// NetworkSpecServiceType Service type identifier (must be "network")
type NetworkSpecServiceType string

// NetworkStatus Current status of the network service instance.
// PENDING: LoadBalancer service waiting for external IP assignment.
// READY: Service is operational (ClusterIP/NodePort immediately, LoadBalancer after IP assigned).
// DELETED: Service resource not found in cluster.
type NetworkStatus string

// PortSpec Port definition for a network service
type PortSpec struct {
	// Name Port name (required when multiple ports are defined)
	//
	// Example: http
	Name *string `json:"name,omitempty"`

	// NodePort Allocated NodePort value (response only, auto-assigned or from provider_hints)
	//
	// Example: 31234
	NodePort *int32 `json:"node_port,omitempty"`

	// Port Service port number
	//
	// Example: 80
	Port int32 `json:"port"`

	// Protocol Network protocol
	//
	// Example: TCP
	Protocol *PortSpecProtocol `json:"protocol,omitempty"`

	// TargetPort Target port on the backing pods
	//
	// Example: 8080
	TargetPort *int32 `json:"target_port,omitempty"`
}

// PortSpecProtocol Network protocol
//
// Example: TCP
type PortSpecProtocol string

// ProviderHints Provider-specific hints from the catalog
type ProviderHints struct {
	// Kubernetes Kubernetes-specific Service settings (request only)
	Kubernetes           *KubernetesProviderHints `json:"kubernetes,omitempty"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// NetworkIdPath defines model for NetworkIdPath.
type NetworkIdPath = string

// ListNetworksParams defines parameters for ListNetworks.
type ListNetworksParams struct {
	// MaxPageSize Maximum number of resources per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateNetworkParams defines parameters for CreateNetwork.
type CreateNetworkParams struct {
	// Id Optional client-specified ID for the network. If not provided,
	// the server will generate an ID.
	//
	// Requirements (per AEP-122):
	// - 1-63 characters long
	// - Start with a lowercase letter or digit
	// - Contain only lowercase letters, numbers, and hyphens
	// - End with letter or number
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateNetworkJSONRequestBody defines body for CreateNetwork for application/json ContentType.
type CreateNetworkJSONRequestBody = Network

// Getter for additional properties for ProviderHints. Returns the specified
// element and whether it was found
func (a ProviderHints) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProviderHints
func (a *ProviderHints) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a *ProviderHints) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["kubernetes"]; found {
		err = json.Unmarshal(raw, &a.Kubernetes)
		if err != nil {
			return fmt.Errorf("error reading 'kubernetes': %w", err)
		}
		delete(object, "kubernetes")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a ProviderHints) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Kubernetes != nil {
		object["kubernetes"], err = json.Marshal(a.Kubernetes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'kubernetes': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
